SHOW ENGINES;

SHOW TABLES;

CREATE TABLE barang
(
    id     INT          NOT NULL,
    nama   VARCHAR(100) NOT NULL,
    harga  INT          NOT NULL DEFAULT 0,
    jumlah INT          NOT NULL DEFAULT 0
) ENGINE = InnoDB;

-- UNTUK MELIHAT ISI DIDALEM TABEL
DESCRIBE barang;

-- UNTUK MELIHAT STRUKTUR PADA TABEL
SHOW CREATE TABLE barang;

-- CONTOH UNTUK MENAMBAHKAN ISI TABLE
ALTER TABLE barang
    ADD COLUMN deskripsi TEXT;

-- CONTOH UNTUK MENGHAPUS DATA PADA TABEL
ALTER TABLE barang
    ADD COLUMN salah TEXT;
ALTER TABLE barang
    DROP COLUMN deskripsi;

-- UNTUK MEMODIFIKASI ISI TABEL DAN "NAMA" MENJADI ADA DI SETELAH DESKRIPSI
ALTER TABLE barang
    MODIFY nama VARCHAR(200) AFTER deskripsi;

-- UNTUK MENGUBAG STRUKTUR PADA TABEL MENJADI URUTAN PALING ATAS
ALTER TABLE barang
    MODIFY nama VARCHAR(200) FIRST;

ALTER TABLE barang
    MODIFY id INT;

ALTER TABLE barang
    MODIFY id INT NOT NULL;

ALTER TABLE barang
    MODIFY deskripsi text NOT NULL;

SHOW CREATE TABLE barang;

ALTER TABLE barang
    MODIFY jumlah INT NOT NULL DEFAULT 0;

ALTER TABLE barang
    MODIFY harga INT NOT NULL DEFAULT 0;

ALTER TABLE barang
    ADD waktu_dibuat TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

INSERT INTO barang (id, nama)
VALUES (1, 'Apel');

SELECT *
FROM barang;

# UNTUK MENGHAPUS SEMUA DATA DALAM TABEL
TRUNCATE barang;

SHOW tables;

DROP TABLE barang;